In [ ]:
#create Array using numpy.empty(shape, dtype=float, order='c')

In [1]:
import numpy as np

In [7]:
b=np.empty(2, dtype=int, order='c')
print("Matrix b : \n",b)

Matrix b : 
 [0 0]


In [5]:
a=np.empty([2,2], dtype=int)
print("\nMatrix a : \n",a)


Matrix a : 
 [[ 149958451 1035807268]
 [ 506081848  519027648]]


In [6]:
c=np.empty([3,3])
print("\nMatrix c: \n",c)


Matrix c: 
 [[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [4.22788818e-307 2.67019049e-306 1.42413555e-306]
 [1.78019082e-306 4.79243676e-322 0.00000000e+000]]
