In [1]:
#Create Array using numpy.zeros(shape, dtype=None, order='c')

In [2]:
import numpy as np

In [3]:
b=np.zeros(2, dtype=int)
print("Matrix b: \n", b)

Matrix b: 
 [0 0]


In [4]:
a= np.zeros([2,2], dtype=int)
print("\nMatrix a:\n",a)


Matrix a:
 [[0 0]
 [0 0]]


In [5]:
c=np.zeros([3,3])
print("\nMatrix c:\n",c)


Matrix c:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
